# Generated by Django 2.0.2 on 2018-03-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_identify', models.CharField(max_length=50, null=True)),
                ('book_name', models.CharField(max_length=50, null=True, verbose_name='书名')),
                ('book_image', models.CharField(max_length=200, null=True, verbose_name='封面')),
                ('book_author', models.CharField(max_length=50, null=True, verbose_name='作者')),
                ('book_category', models.CharField(max_length=50, null=True, verbose_name='分类')),
                ('book_latest', models.CharField(max_length=50, null=True, verbose_name='更新时间')),
                ('book_createTime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('book_desc', models.CharField(max_length=1000, null=True, verbose_name='简介')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chap_id', models.AutoField(primary_key=True, serialize=False)),
                ('chap_identify', models.IntegerField()),
                ('chap_title', models.CharField(max_length=100, null=True, verbose_name='章节')),
                ('chap_createTime', models.DateTimeField(auto_now=True, null=True, verbose_name='添加时间')),
                ('chap_contentUrl', models.CharField(max_length=100, null=True, verbose_name='内容链接')),
                ('book_identify', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
