# Generated by Django 2.0.2 on 2018-03-05 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_createTime',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chap_createTime',
        ),
        migrations.AddField(
            model_name='books',
            name='book_clect',
            field=models.ImageField(default=0, upload_to='', verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='books',
            name='book_click',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='books',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
