# Generated by Django 2.0.2 on 2018-03-05 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_auto_20180305_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('create_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': '小说名', 'verbose_name_plural': '小说名'},
        ),
    ]
