# Generated by Django 2.0.2 on 2018-03-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_auto_20180305_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelcategory',
            name='category_id',
            field=models.ImageField(default=0, max_length=50, upload_to='', verbose_name='分类id'),
        ),
    ]
